version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - GITHUB_ID=${GIT}
      - GITHUB_SECRET=${GIT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
    volumes:
      - .:/app
      - /app/node_modules

# Uncomment and configure this if you need a local MongoDB instance
# db:
#   image: mongo
#   ports:
#     - 27017:27017
#   environment:
#     - MONGO_INITDB_ROOT_USERNAME=antenmanuuel
#     - MONGO_INITDB_ROOT_PASSWORD=anten
#   volumes:
#     - tasked:/data/db

volumes:
  tasked:
